### ISSUE TITLE
Can't paste an image into LiveCode

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#877] opened 2016-02-08 14:21 UTC
Go to Google Images, copy an image, try to paste in into LiveCode.

This works in 7.1 but nothing happens in 8.0-dp14.

**Comment by peter-b** [comment] 2016-03-24 09:12
This appears to be a duplicate of [bug 17216](http://quality.livecode.com/show_bug.cgi?id=17216).

**Closed as completed by peter-b** 2016-03-24 09:12 UTC
Labels: bug
